# Generated by Django 5.2.4 on 2025-07-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客文章', 'verbose_name_plural': '博客文章管理'},
        ),
    ]
